In [1]:
## 강의에서 사용될 라이브러리를 먼저 임포트 해 보자.

import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

# 시각화 라이브러리
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

%matplotlib inline

%precision 3

'%.3f'

## Numpy 기초

In [21]:
# 배열(array)의 작성

data = np.array([9,2,3,4,10,6,7,8,1,5])

data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [9]:
len(data)

10

In [10]:
data.dtype

dtype('int64')

In [11]:
# 참고 : data type (int8,16,32,64, uint8,16,32,64, float16,32,64,128, bool 등)

In [12]:
# 차원 수와 요소 수

print("차원 수", data.ndim)

print("요소 수", data.size)

차원 수 1
요소 수 10


In [13]:
# 모든 요소에 대한 계산 (casting)

data * 2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [16]:
print("multiplication", np.array([1,2,3,4,5]) * np.array([5,4,3,2,1]))

print("devision", np.array([1,2,3,4,5]) * np.array([5,4,3,2,1]))

print("powers", np.array([1,2,3,4,5]) ** 2)


multiplication [5 8 9 8 5]
devision [5 8 9 8 5]
powers [ 1  4  9 16 25]


In [22]:
# sorting

print("원래 :", data)

원래 : [ 9  2  3  4 10  6  7  8  1  5]


In [23]:
data.sort()
print("정렬 후 :", data)

정렬 후 : [ 1  2  3  4  5  6  7  8  9 10]


In [30]:
# list.sort()의 reverse= True는 넘파이 어레이에는 적용 안 됨

data.sort()
print("정렬 후 :", data[::-1])

정렬 후 : [10  9  8  7  6  5  4  3  2  1]


In [26]:
# min, max, sum, cumsum, ration

print("min :", data.min())
print("max :", data.max())
print("sum :", data.sum())
print("cumsum :", data.cumsum())
print("ration :", data.cumsum()/data.sum())

min : 1
max : 10
sum : 55
cumsum : [10 19 27 34 40 45 49 52 54 55]
ration : [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


In [31]:
# 난수 (random number generation)

import numpy.random as random

# random seed

random.seed(777)

In [33]:
# randn(정규분포의 난수를 n개 발생)
random.randn(3)

array([ 1.244, -0.149,  0.172])

### numpy random module의 아래의 링크를 일독할 가치가 있다.

https://numpy.org/doc/stable/reference/random/index.html

In [41]:
# 복원추출과 비복원추출

random.seed(0)

data = np.array([9,2,3,4,10,6,7,8,1,5])

#복원추출
print(random.choice(data,10))

#비복원추출
print(random.choice(data,10, replace = False))

[ 6  9  4  4  8  5  4  6  3 10]
[ 1  4  6  2  3 10  5  9  7  8]


In [45]:
# Vector

vec = np.arange(9)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
# matrix

mat = np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
# 1 행
mat[0, :]

array([0, 1, 2])

In [48]:
# 1 열
mat[:,0]

array([0, 3, 6])

In [50]:
mat[:2,:2]

array([[0, 1],
       [3, 4]])

In [51]:
# 행렬 연산

mat_2 = np.arange(9,18).reshape(3,3)
mat_2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [52]:
# 행렬의 내적 연산

np.dot(mat, mat_2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [53]:
# 행렬 곱(element-wise)

mat * mat_2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [54]:
# 특수 행렬

print(np.zeros((2,3), dtype = np.int64))
print(np.ones((3,4), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 기타 행렬과 관련된 역행렬, 고유값, 고유벡터, 최적화 등은 scipy module을 활용한다.

https://docs.scipy.org/doc/scipy/tutorial/index.html